services:
  citus:
    build:
      context: .
    image: "citusdata/citus"
    container_name: ${PG_CONTAINER_NAME}
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./migrations/migrations.sql:/docker-entrypoint-initdb.d/20230831073740_setup.up.sql
      - ./data/airlines.csv:/docker-entrypoint-initdb.d/airlines.csv
      - ./data/airports.csv:/docker-entrypoint-initdb.d/airports.csv
      - ./data/flights.csv:/docker-entrypoint-initdb.d/flights.csv
    ports:
      - "5432:5432"
    restart: unless-stopped